// <auto-generated />
using System;
using Clinique2000_DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinique2000_DataAccess.Migrations
{
    [DbContext(typeof(CliniqueDbContext))]
    [Migration("20240207015110_ajoutAdminSeed")]
    partial class ajoutAdminSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Clinique2000_Core.Models.Adresse", b =>
                {
                    b.Property<int>("AdresseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdresseID"), 1L, 1);

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("AdresseID");

                    b.ToTable("Adresses");

                    b.HasData(
                        new
                        {
                            AdresseID = 1,
                            CodePostal = "J4G 2M6",
                            Numero = "505",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Rue Adoncour",
                            Ville = "Longueuil"
                        },
                        new
                        {
                            AdresseID = 2,
                            CodePostal = "J4M 2X1",
                            Numero = "1615",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Blvd Jacques-Cartier",
                            Ville = "Longueuil"
                        },
                        new
                        {
                            AdresseID = 3,
                            CodePostal = "J4K 1E2",
                            Numero = "1144",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Rue Saint-Laurent",
                            Ville = "Longueuil"
                        },
                        new
                        {
                            AdresseID = 4,
                            CodePostal = "J4V 2H2",
                            Numero = "3141",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Blvd Taschereau",
                            Ville = "Longueuil"
                        },
                        new
                        {
                            AdresseID = 5,
                            CodePostal = "H3B 4G1",
                            Numero = "895",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Rue De la Gauchetiére",
                            Ville = "Montreal"
                        },
                        new
                        {
                            AdresseID = 6,
                            CodePostal = "J3Y 3P5",
                            Numero = "5580",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = " Ch. de Chambly B",
                            Ville = "Saint-Hubert"
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.AdressesQuebec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProvinceAbbr")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("TimeZone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdressesQuebec");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Clinique", b =>
                {
                    b.Property<int>("CliniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CliniqueID"), 1L, 1);

                    b.Property<int>("AdresseID")
                        .HasColumnType("int");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateurID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("HeureFermeture")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HeureOuverture")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<string>("NomClinique")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempsMoyenConsultation")
                        .HasColumnType("int");

                    b.HasKey("CliniqueID");

                    b.HasIndex("AdresseID")
                        .IsUnique();

                    b.HasIndex("CreateurID");

                    b.ToTable("Cliniques");

                    b.HasData(
                        new
                        {
                            CliniqueID = 1,
                            AdresseID = 1,
                            Courriel = "contact@adoncour.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 2, 6, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5586),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 15, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Clinique Adoncour",
                            NumTelephone = "(450) 646-4445",
                            TempsMoyenConsultation = 30
                        },
                        new
                        {
                            CliniqueID = 2,
                            AdresseID = 2,
                            Courriel = "contact@pboucher.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 2, 6, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5636),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 22, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Clinique Pierre-Boucher",
                            NumTelephone = "(450) 468-6223",
                            TempsMoyenConsultation = 30
                        },
                        new
                        {
                            CliniqueID = 3,
                            AdresseID = 3,
                            Courriel = "contact@camu.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 2, 6, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5639),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 18, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Clinique Medicale Urgence Camu",
                            NumTelephone = "(450) 679-4333",
                            TempsMoyenConsultation = 20
                        },
                        new
                        {
                            CliniqueID = 4,
                            AdresseID = 4,
                            Courriel = "contact@cigogne.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 2, 6, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5642),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 20, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Medical Clinic GMF La Cigogne",
                            NumTelephone = "(450) 466-7892",
                            TempsMoyenConsultation = 40
                        },
                        new
                        {
                            CliniqueID = 5,
                            AdresseID = 5,
                            Courriel = "contact@cmenroute.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 2, 6, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5644),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 16, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Clinique Medicale en Route",
                            NumTelephone = "(514) 954-1444",
                            TempsMoyenConsultation = 10
                        },
                        new
                        {
                            CliniqueID = 6,
                            AdresseID = 6,
                            Courriel = "contact@chambly.com",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 2, 6, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5650),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 16, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Centre Médical Chambly Latour",
                            NumTelephone = "(450) 926-2236",
                            TempsMoyenConsultation = 15
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Consultation", b =>
                {
                    b.Property<int>("ConsultationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultationID"), 1L, 1);

                    b.Property<DateTime?>("HeureDateDebutReele")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HeureDateFinReele")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ListeAttenteID")
                        .HasColumnType("int");

                    b.Property<int?>("MedecinEmployeCliniqueID")
                        .HasColumnType("int");

                    b.Property<string>("MedecinId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("PlageHoraireID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("StatutConsultation")
                        .HasColumnType("int");

                    b.HasKey("ConsultationID");

                    b.HasIndex("ListeAttenteID");

                    b.HasIndex("MedecinEmployeCliniqueID");

                    b.HasIndex("PatientID");

                    b.HasIndex("PlageHoraireID");

                    b.ToTable("Consultations");

                    b.HasData(
                        new
                        {
                            ConsultationID = 1,
                            PatientID = 1,
                            PlageHoraireID = 1,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 2,
                            PatientID = 2,
                            PlageHoraireID = 1,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 3,
                            PatientID = 3,
                            PlageHoraireID = 2,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 4,
                            PatientID = 4,
                            PlageHoraireID = 2,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 5,
                            PatientID = 5,
                            PlageHoraireID = 3,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 6,
                            PatientID = 6,
                            PlageHoraireID = 3,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 7,
                            PatientID = 7,
                            PlageHoraireID = 4,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 8,
                            PatientID = 8,
                            PlageHoraireID = 4,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 9,
                            PatientID = 9,
                            PlageHoraireID = 5,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 10,
                            PatientID = 10,
                            PlageHoraireID = 5,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 11,
                            PatientID = 11,
                            PlageHoraireID = 6,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 12,
                            PatientID = 12,
                            PlageHoraireID = 6,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 13,
                            PatientID = 13,
                            PlageHoraireID = 7,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 14,
                            PatientID = 14,
                            PlageHoraireID = 7,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 15,
                            PatientID = 15,
                            PlageHoraireID = 8,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 16,
                            PatientID = 16,
                            PlageHoraireID = 8,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 17,
                            PatientID = 17,
                            PlageHoraireID = 9,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 18,
                            PatientID = 18,
                            PlageHoraireID = 9,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 19,
                            PatientID = 19,
                            PlageHoraireID = 10,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 20,
                            PatientID = 20,
                            PlageHoraireID = 10,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 21,
                            PatientID = 21,
                            PlageHoraireID = 11,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 22,
                            PlageHoraireID = 11,
                            StatutConsultation = 6
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.EmployesClinique", b =>
                {
                    b.Property<int>("EmployeCliniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeCliniqueID"), 1L, 1);

                    b.Property<int>("CliniqueID")
                        .HasColumnType("int");

                    b.Property<string>("EmployeCliniqueCourriel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeCliniqueNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeCliniquePosition")
                        .HasColumnType("int");

                    b.Property<string>("EmployeCliniquePrenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EmployeCliniqueID");

                    b.HasIndex("CliniqueID");

                    b.HasIndex("UserID");

                    b.ToTable("EmployesClinique");

                    b.HasData(
                        new
                        {
                            EmployeCliniqueID = 1,
                            CliniqueID = 1,
                            EmployeCliniqueCourriel = "numcliniquetest@gmail.com",
                            EmployeCliniqueNom = "Tremblay",
                            EmployeCliniquePosition = 0,
                            EmployeCliniquePrenom = "Mark"
                        },
                        new
                        {
                            EmployeCliniqueID = 2,
                            CliniqueID = 1,
                            EmployeCliniqueCourriel = "testproject2132@gmail.com",
                            EmployeCliniqueNom = "Dubois",
                            EmployeCliniquePosition = 0,
                            EmployeCliniquePrenom = "Monique"
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ListeAttente", b =>
                {
                    b.Property<int>("ListeAttenteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListeAttenteID"), 1L, 1);

                    b.Property<int>("CliniqueID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEffectivite")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HeureFermeture")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureOuverture")
                        .HasColumnType("time");

                    b.Property<bool>("IsOuverte")
                        .HasColumnType("bit");

                    b.Property<int>("NbMedecinsDispo")
                        .HasColumnType("int");

                    b.HasKey("ListeAttenteID");

                    b.HasIndex("CliniqueID");

                    b.ToTable("ListeAttentes");

                    b.HasData(
                        new
                        {
                            ListeAttenteID = 1,
                            CliniqueID = 1,
                            DateEffectivite = new DateTime(2024, 2, 7, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5685),
                            HeureFermeture = new TimeSpan(0, 14, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 2,
                            CliniqueID = 2,
                            DateEffectivite = new DateTime(2024, 2, 7, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5701),
                            HeureFermeture = new TimeSpan(0, 8, 30, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 1
                        },
                        new
                        {
                            ListeAttenteID = 3,
                            CliniqueID = 3,
                            DateEffectivite = new DateTime(2024, 2, 7, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5709),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 4,
                            CliniqueID = 4,
                            DateEffectivite = new DateTime(2024, 2, 7, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5716),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 5,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 2, 7, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5760),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 6,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 2, 7, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5770),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 7,
                            CliniqueID = 2,
                            DateEffectivite = new DateTime(2024, 2, 8, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5777),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 8,
                            CliniqueID = 2,
                            DateEffectivite = new DateTime(2024, 2, 8, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5784),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 9,
                            CliniqueID = 3,
                            DateEffectivite = new DateTime(2024, 2, 8, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5791),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 10,
                            CliniqueID = 4,
                            DateEffectivite = new DateTime(2024, 2, 10, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5799),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 11,
                            CliniqueID = 4,
                            DateEffectivite = new DateTime(2024, 2, 11, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5806),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 12,
                            CliniqueID = 4,
                            DateEffectivite = new DateTime(2024, 2, 12, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5812),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 13,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 2, 9, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5819),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 14,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 2, 10, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5826),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 15,
                            CliniqueID = 1,
                            DateEffectivite = new DateTime(2024, 2, 9, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5833),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 16,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 2, 10, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5841),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 17,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 2, 11, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5847),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 18,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 2, 12, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5855),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 19,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 2, 7, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5862),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 20,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 2, 8, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5869),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 21,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 2, 9, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5876),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 22,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 2, 10, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5883),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 23,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 2, 11, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5892),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 24,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 2, 12, 20, 51, 9, 512, DateTimeKind.Local).AddTicks(5899),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 3
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("DateDeNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAM")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Age = 32,
                            CodePostal = "J4J 1Z4",
                            DateDeNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Masculin",
                            NAM = "EASC 2342 4332",
                            Nom = "Eastwood",
                            Prenom = "Clint",
                            UserId = "7cc96785-8933-4eac-8d7f-a289b28df223"
                        },
                        new
                        {
                            PatientId = 2,
                            Age = 27,
                            CodePostal = "J4J 1V2",
                            DateDeNaissance = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Féminin",
                            NAM = "BLUE 4232 4332",
                            Nom = "Blunt",
                            Prenom = "Emily",
                            UserId = "e2b8f367-6c94-4a3e-b5a6-45dabec4d2e2"
                        },
                        new
                        {
                            PatientId = 3,
                            Age = 36,
                            CodePostal = "J4J 1G4",
                            DateDeNaissance = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Masculin",
                            NAM = "MARB 3244 2233",
                            Nom = "Brando",
                            Prenom = "Marlon",
                            UserId = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f3f3"
                        },
                        new
                        {
                            PatientId = 4,
                            Age = 44,
                            CodePostal = "J4J 1H6",
                            DateDeNaissance = new DateTime(1980, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Féminin",
                            NAM = "PORT 3443 3433",
                            Nom = "Portman",
                            Prenom = "Natalie",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g4g4"
                        },
                        new
                        {
                            PatientId = 5,
                            Age = 53,
                            CodePostal = "V9S 1N2",
                            DateDeNaissance = new DateTime(1971, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "TREA 1234 4569",
                            Nom = "Tremblay",
                            Prenom = "Anne",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g4g5"
                        },
                        new
                        {
                            PatientId = 6,
                            Age = 28,
                            CodePostal = "C1U 7Y0",
                            DateDeNaissance = new DateTime(1996, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "LAVJ 1234 4570",
                            Nom = "Lavoie",
                            Prenom = "Jean",
                            UserId = "7cc96785-8933-4eac-8d7f-a289b28df226"
                        },
                        new
                        {
                            PatientId = 7,
                            Age = 33,
                            CodePostal = "T5E 4Z2",
                            DateDeNaissance = new DateTime(1991, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "GAGA 1234 4571",
                            Nom = "Gagnon",
                            Prenom = "Andrew",
                            UserId = "e2b8f367-6c94-4a3e-b5a6-45dabec4d2e7"
                        },
                        new
                        {
                            PatientId = 8,
                            Age = 42,
                            CodePostal = "E9C 8W3",
                            DateDeNaissance = new DateTime(1982, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Female",
                            NAM = "GAUJ 1234 4572",
                            Nom = "Gauthier",
                            Prenom = "Jean",
                            UserId = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f3f38"
                        },
                        new
                        {
                            PatientId = 9,
                            Age = 29,
                            CodePostal = "H4Z 0C5",
                            DateDeNaissance = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "ROYS 1234 4573",
                            Nom = "Roy",
                            Prenom = "Sophie",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g4g9"
                        },
                        new
                        {
                            PatientId = 10,
                            Age = 74,
                            CodePostal = "D2R 4Q3",
                            DateDeNaissance = new DateTime(1950, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Female",
                            NAM = "GAGJ 1234 4574",
                            Nom = "Gagnon",
                            Prenom = "Julie",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g410"
                        },
                        new
                        {
                            PatientId = 11,
                            Age = 46,
                            CodePostal = "F1G 2H4",
                            DateDeNaissance = new DateTime(1978, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "BOUM 1234 4575",
                            Nom = "Bouchard",
                            Prenom = "Martin",
                            UserId = "7cc96785-8933-4eac-8d7f-a289b28df211"
                        },
                        new
                        {
                            PatientId = 12,
                            Age = 36,
                            CodePostal = "J3K 5L8",
                            DateDeNaissance = new DateTime(1988, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Female",
                            NAM = "COUA 1234 4576",
                            Nom = "Couto",
                            Prenom = "Anne",
                            UserId = "e2b8f367-6c94-4a3e-b5a6-45dabec4d212"
                        },
                        new
                        {
                            PatientId = 13,
                            Age = 32,
                            CodePostal = "K2L 6M8",
                            DateDeNaissance = new DateTime(1992, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Female",
                            NAM = "FORJ 1234 4577",
                            Nom = "Fortin",
                            Prenom = "Julie",
                            UserId = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f313"
                        },
                        new
                        {
                            PatientId = 14,
                            Age = 30,
                            CodePostal = "X8F 4I7",
                            DateDeNaissance = new DateTime(1994, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Female",
                            NAM = "FORM 1234 4578",
                            Nom = "Fortin",
                            Prenom = "Martin",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g414"
                        },
                        new
                        {
                            PatientId = 15,
                            Age = 39,
                            CodePostal = "S9K 3Z3",
                            DateDeNaissance = new DateTime(1985, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "MORC 1234 4579",
                            Nom = "Morin",
                            Prenom = "Claire",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g415"
                        },
                        new
                        {
                            PatientId = 16,
                            Age = 39,
                            CodePostal = "H3N 3Z8",
                            DateDeNaissance = new DateTime(1985, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "ROYC 1234 4580",
                            Nom = "Roy",
                            Prenom = "Claire",
                            UserId = "7cc96785-8933-4eac-8d7f-a289b28df216"
                        },
                        new
                        {
                            PatientId = 17,
                            Age = 66,
                            CodePostal = "M1F 6Z2",
                            DateDeNaissance = new DateTime(1958, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Female",
                            NAM = "GAUL 1234 4581",
                            Nom = "Gauthier",
                            Prenom = "Louis",
                            UserId = "e2b8f367-6c94-4a3e-b5a6-45dabec4d217"
                        },
                        new
                        {
                            PatientId = 18,
                            Age = 74,
                            CodePostal = "G3W 7Q1",
                            DateDeNaissance = new DateTime(1950, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "COUM 1234 4582",
                            Nom = "Couto",
                            Prenom = "Marie",
                            UserId = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f318"
                        },
                        new
                        {
                            PatientId = 19,
                            Age = 49,
                            CodePostal = "D1D 3D9",
                            DateDeNaissance = new DateTime(1975, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "MORM 1234 4583",
                            Nom = "Morin",
                            Prenom = "Michel",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g419"
                        },
                        new
                        {
                            PatientId = 20,
                            Age = 69,
                            CodePostal = "M4F 2S8",
                            DateDeNaissance = new DateTime(1955, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "ROYM 1234 4584",
                            Nom = "Roy",
                            Prenom = "Martin",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g420"
                        },
                        new
                        {
                            PatientId = 21,
                            Age = 70,
                            CodePostal = "M4F 2S8",
                            DateDeNaissance = new DateTime(1954, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "ROYM 1234 4585",
                            Nom = "Roy",
                            Prenom = "Matheo",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g421"
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PatientACharge", b =>
                {
                    b.Property<int>("PatientAChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientAChargeId"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDeNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("NAM")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("PatientAChargeId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientACharges");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PlageHoraire", b =>
                {
                    b.Property<int>("PlageHoraireID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlageHoraireID"), 1L, 1);

                    b.Property<DateTime>("HeureDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HeureFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListeAttenteID")
                        .HasColumnType("int");

                    b.HasKey("PlageHoraireID");

                    b.HasIndex("ListeAttenteID");

                    b.ToTable("PlagesHoraires");

                    b.HasData(
                        new
                        {
                            PlageHoraireID = 1,
                            HeureDebut = new DateTime(2024, 2, 7, 8, 0, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 2, 7, 8, 30, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 2,
                            HeureDebut = new DateTime(2024, 2, 7, 8, 30, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 2, 7, 9, 0, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 3,
                            HeureDebut = new DateTime(2024, 2, 7, 9, 0, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 2, 7, 9, 30, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 4,
                            HeureDebut = new DateTime(2024, 2, 7, 9, 30, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 2, 7, 10, 0, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 5,
                            HeureDebut = new DateTime(2024, 2, 7, 10, 0, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 2, 7, 10, 30, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 6,
                            HeureDebut = new DateTime(2024, 2, 7, 10, 30, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 2, 7, 11, 0, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 7,
                            HeureDebut = new DateTime(2024, 2, 7, 11, 0, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 2, 7, 11, 30, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 8,
                            HeureDebut = new DateTime(2024, 2, 7, 11, 30, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 2, 7, 12, 0, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 9,
                            HeureDebut = new DateTime(2024, 2, 7, 12, 0, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 2, 7, 12, 30, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 10,
                            HeureDebut = new DateTime(2024, 2, 7, 12, 30, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 2, 7, 13, 0, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 11,
                            HeureDebut = new DateTime(2024, 2, 7, 13, 0, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 2, 7, 13, 30, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cf4f43ff-24d2-4d64-85c5-267bbf27abff",
                            Email = "patient1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT1@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT1@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f810d62c-3eec-45a3-a726-872bab667357",
                            TwoFactorEnabled = false,
                            UserName = "patient1@example.com"
                        },
                        new
                        {
                            Id = "e2b8f367-6c94-4a3e-b5a6-45dabec4d2e2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ad536d00-70e8-42d7-8b94-fe97ab1b715e",
                            Email = "patient2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT2@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT2@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "369a1c8b-82d3-45b0-b389-92884835bfa9",
                            TwoFactorEnabled = false,
                            UserName = "patient2@example.com"
                        },
                        new
                        {
                            Id = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f3f3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6aed1a31-b1c0-4d47-8653-78d2ba3de565",
                            Email = "patient3@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT3@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT3@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a641dfb8-8a1f-4771-a30b-a1709e1b7819",
                            TwoFactorEnabled = false,
                            UserName = "patient3@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g4g4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "93fe1a28-529a-45ad-89fc-e7cb1208d19f",
                            Email = "patient4@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT4@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT4@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7cd1f84a-16d4-46fd-b1d3-851662d962c4",
                            TwoFactorEnabled = false,
                            UserName = "patient4@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g4g5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1eb58b0f-07ea-4355-9808-242bd5aa6862",
                            Email = "patient5@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT5@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT5@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dea42399-911a-494b-96b9-abc80b46f4c8",
                            TwoFactorEnabled = false,
                            UserName = "patient5@example.com"
                        },
                        new
                        {
                            Id = "7cc96785-8933-4eac-8d7f-a289b28df226",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a5238559-b12b-42d8-9a39-a173a79600b8",
                            Email = "patient6@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT6@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT6@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "29f5d543-7f24-4ac6-8b69-78a9eabba11b",
                            TwoFactorEnabled = false,
                            UserName = "patient6@example.com"
                        },
                        new
                        {
                            Id = "e2b8f367-6c94-4a3e-b5a6-45dabec4d2e7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4691e5fe-0cc6-4f52-890b-bcafdde668c1",
                            Email = "patient7@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT7@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT7@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ce0a163b-0b62-4374-b3e4-20ee33ca7d30",
                            TwoFactorEnabled = false,
                            UserName = "patient7@example.com"
                        },
                        new
                        {
                            Id = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f3f38",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "644fcd21-073f-469c-a606-ba054243b246",
                            Email = "patient8@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT8@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT8@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b0dc7bdd-c8d5-4d18-9d9a-0bae1b7ce631",
                            TwoFactorEnabled = false,
                            UserName = "patient8@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g4g9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b8924dd0-ba6d-4c33-971a-ec5ce0e60da4",
                            Email = "patient9@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT9@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT9@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "22e38c93-2de1-4936-979b-2a1b3c17db19",
                            TwoFactorEnabled = false,
                            UserName = "patient9@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g410",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4df8a991-4c37-47f2-b5cf-648d40dafbd9",
                            Email = "patient10@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT10@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT10@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a8156349-29ed-42e9-a749-f730231d6807",
                            TwoFactorEnabled = false,
                            UserName = "patient10@example.com"
                        },
                        new
                        {
                            Id = "7cc96785-8933-4eac-8d7f-a289b28df211",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d7417ee1-1a14-440f-9579-6ec6cef64910",
                            Email = "patient11@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT11@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT11@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9732b730-2a37-4f02-8db7-b775d28680a6",
                            TwoFactorEnabled = false,
                            UserName = "patient11@example.com"
                        },
                        new
                        {
                            Id = "e2b8f367-6c94-4a3e-b5a6-45dabec4d212",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cf552670-7213-41e8-b87c-c823ba2edaba",
                            Email = "patient12@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT12@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT12@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "77417234-a93f-46e9-aaab-1dae45670054",
                            TwoFactorEnabled = false,
                            UserName = "patient12@example.com"
                        },
                        new
                        {
                            Id = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f313",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cff01027-012c-49d1-93d7-266891716844",
                            Email = "patient13@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT13@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT13@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a3f34973-7dcb-4485-aedf-99c3e4209b99",
                            TwoFactorEnabled = false,
                            UserName = "patient13@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g414",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "adfc5b0f-1c8d-40b2-bc3d-5b3f610ddde5",
                            Email = "patient14@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT14@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT14@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e40ac34f-5267-49e8-a53b-0f4d2961bda1",
                            TwoFactorEnabled = false,
                            UserName = "patient14@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g415",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "76a34158-c3ce-478d-8f54-bc6cbea10c95",
                            Email = "patient15@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT15@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT15@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "596af4cc-5a4f-40e6-81c3-8fd9df23952a",
                            TwoFactorEnabled = false,
                            UserName = "patient15@example.com"
                        },
                        new
                        {
                            Id = "7cc96785-8933-4eac-8d7f-a289b28df216",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe552a62-aa04-4c88-855a-e46993e9b48f",
                            Email = "patient16@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT16@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT16@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b4e0731c-7b73-4f8e-8abc-21e6b0733171",
                            TwoFactorEnabled = false,
                            UserName = "patient16@example.com"
                        },
                        new
                        {
                            Id = "e2b8f367-6c94-4a3e-b5a6-45dabec4d217",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8da69191-9991-4fa0-9b64-a5107ba812b1",
                            Email = "patient17@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT17@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT17@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7e6d718e-d1fd-4f3e-a1c2-da1936d24b1c",
                            TwoFactorEnabled = false,
                            UserName = "patient17@example.com"
                        },
                        new
                        {
                            Id = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f318",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b773a561-c62b-4b6f-b1f9-4a377b39ae72",
                            Email = "patient18@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT18@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT18@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6e894018-2b7f-448a-a54d-bf8d49d345e1",
                            TwoFactorEnabled = false,
                            UserName = "patient18@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g419",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8f4c2f43-fa53-4a3a-ae2c-93b4c4cb2b1f",
                            Email = "patient19@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT19@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT19@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cf58b3c3-187c-4f7a-920e-0dc8b6af6e21",
                            TwoFactorEnabled = false,
                            UserName = "patient19@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g420",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57d3b072-1040-4573-beeb-f01e6b87df2b",
                            Email = "patient20@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT20@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT20@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "364e16d0-02d9-4495-806d-0439e1742e44",
                            TwoFactorEnabled = false,
                            UserName = "patient20@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g421",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cc2d6ba7-e1ef-4a30-8400-e3e5de2961cc",
                            Email = "patient21@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT21@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT21@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1dcb3ce7-f12e-48e8-86c9-b8eaaa708aac",
                            TwoFactorEnabled = false,
                            UserName = "patient21@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g22",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "96e7da6e-ac64-4b6e-a443-3362ad7d4e41",
                            Email = "patient22@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT22@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT22@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7aa4d718-36e4-46e9-a88c-c44ef43f00c4",
                            TwoFactorEnabled = false,
                            UserName = "patient22@example.com"
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Clinique", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.Adresse", "Adresse")
                        .WithOne("Clinique")
                        .HasForeignKey("Clinique2000_Core.Models.Clinique", "AdresseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinique2000_Core.Models.ApplicationUser", "Createur")
                        .WithMany("Clinique")
                        .HasForeignKey("CreateurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adresse");

                    b.Navigation("Createur");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Consultation", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.ListeAttente", null)
                        .WithMany("Consultations")
                        .HasForeignKey("ListeAttenteID");

                    b.HasOne("Clinique2000_Core.Models.EmployesClinique", "Medecin")
                        .WithMany()
                        .HasForeignKey("MedecinEmployeCliniqueID");

                    b.HasOne("Clinique2000_Core.Models.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientID");

                    b.HasOne("Clinique2000_Core.Models.PlageHoraire", "PlageHoraire")
                        .WithMany("Consultations")
                        .HasForeignKey("PlageHoraireID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medecin");

                    b.Navigation("Patient");

                    b.Navigation("PlageHoraire");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.EmployesClinique", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.Clinique", "Clinique")
                        .WithMany("EmployesCliniques")
                        .HasForeignKey("CliniqueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinique2000_Core.Models.ApplicationUser", "User")
                        .WithMany("EmployesCliniques")
                        .HasForeignKey("UserID");

                    b.Navigation("Clinique");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ListeAttente", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.Clinique", "Clinique")
                        .WithMany("ListeAttente")
                        .HasForeignKey("CliniqueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinique");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Patient", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.ApplicationUser", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Clinique2000_Core.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PatientACharge", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.Patient", "Patient")
                        .WithMany("PatientsACharge")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PlageHoraire", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.ListeAttente", "ListeAttente")
                        .WithMany("PlagesHoraires")
                        .HasForeignKey("ListeAttenteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListeAttente");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Adresse", b =>
                {
                    b.Navigation("Clinique")
                        .IsRequired();
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Clinique", b =>
                {
                    b.Navigation("EmployesCliniques");

                    b.Navigation("ListeAttente");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ListeAttente", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("PlagesHoraires");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Patient", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("PatientsACharge");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PlageHoraire", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ApplicationUser", b =>
                {
                    b.Navigation("Clinique");

                    b.Navigation("EmployesCliniques");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
