// <auto-generated />
using System;
using Clinique2000_DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinique2000_DataAccess.Migrations
{
    [DbContext(typeof(CliniqueDbContext))]
    [Migration("20240125201535_ModifSeedPatient")]
    partial class ModifSeedPatient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Clinique2000_Core.Models.Adresse", b =>
                {
                    b.Property<int>("AdresseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdresseID"), 1L, 1);

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("AdresseID");

                    b.ToTable("Adresses");

                    b.HasData(
                        new
                        {
                            AdresseID = 1,
                            CodePostal = "J4G 2M6",
                            Numero = "505",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Rue Adoncour",
                            Ville = "Longueuil"
                        },
                        new
                        {
                            AdresseID = 2,
                            CodePostal = "J4M 2X1",
                            Numero = "1615",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Blvd Jacques-Cartier",
                            Ville = "Longueuil"
                        },
                        new
                        {
                            AdresseID = 3,
                            CodePostal = "J4K 1E2",
                            Numero = "1144",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Rue Saint-Laurent",
                            Ville = "Longueuil"
                        },
                        new
                        {
                            AdresseID = 4,
                            CodePostal = "J4V 2H2",
                            Numero = "3141",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Blvd Taschereau",
                            Ville = "Longueuil"
                        },
                        new
                        {
                            AdresseID = 5,
                            CodePostal = "H3B 4G1",
                            Numero = "895",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Rue De la Gauchetière",
                            Ville = "Montreal"
                        },
                        new
                        {
                            AdresseID = 6,
                            CodePostal = "J3Y 3P5",
                            Numero = "5580",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = " Ch. de Chambly B",
                            Ville = "Saint-Hubert"
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Clinique", b =>
                {
                    b.Property<int>("CliniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CliniqueID"), 1L, 1);

                    b.Property<int>("AdresseID")
                        .HasColumnType("int");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateurID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("HeureFermeture")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HeureOuverture")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<string>("NomClinique")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempsMoyenConsultation")
                        .HasColumnType("int");

                    b.HasKey("CliniqueID");

                    b.HasIndex("AdresseID")
                        .IsUnique();

                    b.HasIndex("CreateurID");

                    b.ToTable("Cliniques");

                    b.HasData(
                        new
                        {
                            CliniqueID = 1,
                            AdresseID = 1,
                            Courriel = "contact@adoncour.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 1, 25, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(654),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Clinique Adoncour",
                            NumTelephone = "(450) 646-4445",
                            TempsMoyenConsultation = 30
                        },
                        new
                        {
                            CliniqueID = 2,
                            AdresseID = 2,
                            Courriel = "contact@pboucher.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 1, 25, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(695),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 22, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Clinique Pierre-Boucher",
                            NumTelephone = "(450) 468-6223",
                            TempsMoyenConsultation = 30
                        },
                        new
                        {
                            CliniqueID = 3,
                            AdresseID = 3,
                            Courriel = "contact@camu.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 1, 25, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(700),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 18, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Clinique Medicale Urgence Camu",
                            NumTelephone = "(450) 679-4333",
                            TempsMoyenConsultation = 20
                        },
                        new
                        {
                            CliniqueID = 4,
                            AdresseID = 4,
                            Courriel = "contact@cigogne.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 1, 25, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(703),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 20, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Medical Clinic GMF La Cigogne",
                            NumTelephone = "(450) 466-7892",
                            TempsMoyenConsultation = 40
                        },
                        new
                        {
                            CliniqueID = 5,
                            AdresseID = 5,
                            Courriel = "contact@cmenroute.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 1, 25, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(706),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 16, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Clinique Medicale en Route",
                            NumTelephone = "(514) 954-1444",
                            TempsMoyenConsultation = 10
                        },
                        new
                        {
                            CliniqueID = 6,
                            AdresseID = 6,
                            Courriel = "contact@chambly.com",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 1, 25, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(709),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 16, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Centre Médical Chambly Latour",
                            NumTelephone = "(450) 926-2236",
                            TempsMoyenConsultation = 15
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Consultation", b =>
                {
                    b.Property<int>("ConsultationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultationID"), 1L, 1);

                    b.Property<DateTime>("HeureDateDebutPrevue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HeureDateDebutReele")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HeureDateFinPrevue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HeureDateFinReele")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ListeAttenteID")
                        .HasColumnType("int");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("PlageHoraireID")
                        .HasColumnType("int");

                    b.Property<int>("StatutConsultation")
                        .HasColumnType("int");

                    b.HasKey("ConsultationID");

                    b.HasIndex("ListeAttenteID");

                    b.HasIndex("PatientID");

                    b.HasIndex("PlageHoraireID");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ListeAttente", b =>
                {
                    b.Property<int>("ListeAttenteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListeAttenteID"), 1L, 1);

                    b.Property<int>("CliniqueID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEffectivite")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DureeConsultationMinutes")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HeureFermeture")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureOuverture")
                        .HasColumnType("time");

                    b.Property<bool>("IsOuverte")
                        .HasColumnType("bit");

                    b.Property<int>("NbMedecinsDispo")
                        .HasColumnType("int");

                    b.HasKey("ListeAttenteID");

                    b.HasIndex("CliniqueID");

                    b.ToTable("ListeAttentes");

                    b.HasData(
                        new
                        {
                            ListeAttenteID = 1,
                            CliniqueID = 1,
                            DateEffectivite = new DateTime(2024, 1, 26, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(735),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 8, 30, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 1
                        },
                        new
                        {
                            ListeAttenteID = 2,
                            CliniqueID = 2,
                            DateEffectivite = new DateTime(2024, 1, 26, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(752),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 3,
                            CliniqueID = 3,
                            DateEffectivite = new DateTime(2024, 1, 26, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(766),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 4,
                            CliniqueID = 4,
                            DateEffectivite = new DateTime(2024, 1, 26, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(777),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 5,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 1, 26, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(788),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 6,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 1, 26, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(800),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 7,
                            CliniqueID = 1,
                            DateEffectivite = new DateTime(2024, 1, 27, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(810),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 8,
                            CliniqueID = 2,
                            DateEffectivite = new DateTime(2024, 1, 27, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(821),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 9,
                            CliniqueID = 3,
                            DateEffectivite = new DateTime(2024, 1, 27, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(830),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 10,
                            CliniqueID = 4,
                            DateEffectivite = new DateTime(2024, 1, 29, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(842),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 11,
                            CliniqueID = 4,
                            DateEffectivite = new DateTime(2024, 1, 30, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(852),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 12,
                            CliniqueID = 4,
                            DateEffectivite = new DateTime(2024, 1, 31, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(862),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 13,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 1, 28, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(873),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 14,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 1, 29, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(883),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 15,
                            CliniqueID = 1,
                            DateEffectivite = new DateTime(2024, 1, 28, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(892),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 16,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 1, 29, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(902),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 17,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 1, 30, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(994),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 18,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 1, 31, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(1009),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 19,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 1, 26, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(1019),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 20,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 1, 27, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(1030),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 21,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 1, 28, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(1041),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 22,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 1, 29, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(1051),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 23,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 1, 30, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(1061),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 24,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 1, 31, 15, 15, 34, 687, DateTimeKind.Local).AddTicks(1072),
                            DureeConsultationMinutes = 30,
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 3
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("DateDeNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAM")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Age = 32,
                            CodePostal = "J4J 1Z4",
                            DateDeNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Masculin",
                            NAM = "EASC 2342 4332",
                            Nom = "Eastwood",
                            Prenom = "Clint",
                            UserId = "7cc96785-8933-4eac-8d7f-a289b28df223"
                        },
                        new
                        {
                            PatientId = 2,
                            Age = 27,
                            CodePostal = "J4J 1V2",
                            DateDeNaissance = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Féminine",
                            NAM = "BLUE 4232 4332",
                            Nom = "Blunt",
                            Prenom = "Emily",
                            UserId = "e2b8f367-6c94-4a3e-b5a6-45dabec4d2e2"
                        },
                        new
                        {
                            PatientId = 3,
                            Age = 36,
                            CodePostal = "J4J 1G4",
                            DateDeNaissance = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Masculin",
                            NAM = "MARB 3244 2233",
                            Nom = "Brando",
                            Prenom = "Marlon",
                            UserId = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f3f3"
                        },
                        new
                        {
                            PatientId = 4,
                            Age = 42,
                            CodePostal = "J4J 1H6",
                            DateDeNaissance = new DateTime(1980, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Féminine",
                            NAM = "PORT 3443 3433",
                            Nom = "Portman",
                            Prenom = "Natalie",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g4g4"
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PatientACharge", b =>
                {
                    b.Property<int>("PatientAChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientAChargeId"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDeNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("NAM")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("PatientAChargeId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientACharges");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PlageHoraire", b =>
                {
                    b.Property<int>("PlageHoraireID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlageHoraireID"), 1L, 1);

                    b.Property<DateTime>("HeureDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HeureFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListeAttenteID")
                        .HasColumnType("int");

                    b.HasKey("PlageHoraireID");

                    b.HasIndex("ListeAttenteID");

                    b.ToTable("PlagesHoraires");
                });

            modelBuilder.Entity("Clinique2000_Core.ViewModels.AdressesQuebecVM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProvinceAbbr")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("TimeZone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdressesQuebec");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0b3e40cf-51a7-4fb1-878d-0f898a587f22",
                            Email = "patient1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT1@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT1@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3563323d-1b28-4504-8c26-b1fc1058706c",
                            TwoFactorEnabled = false,
                            UserName = "patient1@example.com"
                        },
                        new
                        {
                            Id = "e2b8f367-6c94-4a3e-b5a6-45dabec4d2e2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9238c912-c4cc-4e37-9f45-e2664a798768",
                            Email = "patient2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT2@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT2@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6c7190b5-68ba-4646-ac93-ef6f39253e61",
                            TwoFactorEnabled = false,
                            UserName = "patient2@example.com"
                        },
                        new
                        {
                            Id = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f3f3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d7dc2110-9041-4f50-a674-fe57dc22417b",
                            Email = "patient3@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT3@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT3@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3751e48b-1458-4818-995c-867bd4e5f5d0",
                            TwoFactorEnabled = false,
                            UserName = "patient3@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g4g4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "123293d6-09ad-40db-8f22-56a8724ee307",
                            Email = "patient4@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT4@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT4@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6c25c028-b9ae-4b88-b67d-a3ce814d60bb",
                            TwoFactorEnabled = false,
                            UserName = "patient4@example.com"
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Clinique", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.Adresse", "Adresse")
                        .WithOne("Clinique")
                        .HasForeignKey("Clinique2000_Core.Models.Clinique", "AdresseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinique2000_Core.Models.ApplicationUser", "Createur")
                        .WithMany("Clinique")
                        .HasForeignKey("CreateurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adresse");

                    b.Navigation("Createur");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Consultation", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.ListeAttente", null)
                        .WithMany("Consultations")
                        .HasForeignKey("ListeAttenteID");

                    b.HasOne("Clinique2000_Core.Models.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientID");

                    b.HasOne("Clinique2000_Core.Models.PlageHoraire", "PlageHorarie")
                        .WithMany("Consultations")
                        .HasForeignKey("PlageHoraireID");

                    b.Navigation("Patient");

                    b.Navigation("PlageHorarie");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ListeAttente", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.Clinique", "Clinique")
                        .WithMany("ListeAttente")
                        .HasForeignKey("CliniqueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinique");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Patient", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.ApplicationUser", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Clinique2000_Core.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PatientACharge", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.Patient", "Patient")
                        .WithMany("PatientsACharge")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PlageHoraire", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.ListeAttente", "ListeAttente")
                        .WithMany("PlagesHoraires")
                        .HasForeignKey("ListeAttenteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListeAttente");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Adresse", b =>
                {
                    b.Navigation("Clinique")
                        .IsRequired();
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Clinique", b =>
                {
                    b.Navigation("ListeAttente");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ListeAttente", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("PlagesHoraires");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Patient", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("PatientsACharge");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PlageHoraire", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ApplicationUser", b =>
                {
                    b.Navigation("Clinique");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
