// <auto-generated />
using System;
using Clinique2000_DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinique2000_DataAccess.Migrations
{
    [DbContext(typeof(CliniqueDbContext))]
    partial class CliniqueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Clinique2000_Core.Models.Adresse", b =>
                {
                    b.Property<int>("AdresseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdresseID"), 1L, 1);

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("AdresseID");

                    b.ToTable("Adresses");

                    b.HasData(
                        new
                        {
                            AdresseID = 1,
                            CodePostal = "J4G 2M6",
                            Numero = "505",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Rue Adoncour",
                            Ville = "Longueuil"
                        },
                        new
                        {
                            AdresseID = 2,
                            CodePostal = "J4M 2X1",
                            Numero = "1615",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Blvd Jacques-Cartier",
                            Ville = "Longueuil"
                        },
                        new
                        {
                            AdresseID = 3,
                            CodePostal = "J4K 1E2",
                            Numero = "1144",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Rue Saint-Laurent",
                            Ville = "Longueuil"
                        },
                        new
                        {
                            AdresseID = 4,
                            CodePostal = "J4V 2H2",
                            Numero = "3141",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Blvd Taschereau",
                            Ville = "Longueuil"
                        },
                        new
                        {
                            AdresseID = 5,
                            CodePostal = "H3B 4G1",
                            Numero = "895",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = "Rue De la Gauchetiére",
                            Ville = "Montreal"
                        },
                        new
                        {
                            AdresseID = 6,
                            CodePostal = "J3Y 3P5",
                            Numero = "5580",
                            Pays = "Canada",
                            Province = "Québec",
                            Rue = " Ch. de Chambly B",
                            Ville = "Saint-Hubert"
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.AdressesQuebec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProvinceAbbr")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("TimeZone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdressesQuebec");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Clinique", b =>
                {
                    b.Property<int>("CliniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CliniqueID"), 1L, 1);

                    b.Property<int>("AdresseID")
                        .HasColumnType("int");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateurID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("HeureFermeture")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HeureOuverture")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<string>("NomClinique")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempsMoyenConsultation")
                        .HasColumnType("int");

                    b.HasKey("CliniqueID");

                    b.HasIndex("AdresseID")
                        .IsUnique();

                    b.HasIndex("CreateurID");

                    b.ToTable("Cliniques");

                    b.HasData(
                        new
                        {
                            CliniqueID = 1,
                            AdresseID = 1,
                            Courriel = "contact@adoncour.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 1, 30, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9541),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 15, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Clinique Adoncour",
                            NumTelephone = "(450) 646-4445",
                            TempsMoyenConsultation = 30
                        },
                        new
                        {
                            CliniqueID = 2,
                            AdresseID = 2,
                            Courriel = "contact@pboucher.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 1, 30, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9591),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 22, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Clinique Pierre-Boucher",
                            NumTelephone = "(450) 468-6223",
                            TempsMoyenConsultation = 30
                        },
                        new
                        {
                            CliniqueID = 3,
                            AdresseID = 3,
                            Courriel = "contact@camu.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 1, 30, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9596),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 18, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Clinique Medicale Urgence Camu",
                            NumTelephone = "(450) 679-4333",
                            TempsMoyenConsultation = 20
                        },
                        new
                        {
                            CliniqueID = 4,
                            AdresseID = 4,
                            Courriel = "contact@cigogne.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 1, 30, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9599),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 20, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Medical Clinic GMF La Cigogne",
                            NumTelephone = "(450) 466-7892",
                            TempsMoyenConsultation = 40
                        },
                        new
                        {
                            CliniqueID = 5,
                            AdresseID = 5,
                            Courriel = "contact@cmenroute.ca",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 1, 30, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9602),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 16, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Clinique Medicale en Route",
                            NumTelephone = "(514) 954-1444",
                            TempsMoyenConsultation = 10
                        },
                        new
                        {
                            CliniqueID = 6,
                            AdresseID = 6,
                            Courriel = "contact@chambly.com",
                            CreateurID = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            DateCreation = new DateTime(2024, 1, 30, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9605),
                            EstActive = true,
                            HeureFermeture = new TimeSpan(0, 16, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            NomClinique = "Centre Médical Chambly Latour",
                            NumTelephone = "(450) 926-2236",
                            TempsMoyenConsultation = 15
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Consultation", b =>
                {
                    b.Property<int>("ConsultationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultationID"), 1L, 1);

                    b.Property<DateTime?>("HeureDateDebutReele")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HeureDateFinReele")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ListeAttenteID")
                        .HasColumnType("int");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("PlageHoraireID")
                        .HasColumnType("int");

                    b.Property<int>("StatutConsultation")
                        .HasColumnType("int");

                    b.HasKey("ConsultationID");

                    b.HasIndex("ListeAttenteID");

                    b.HasIndex("PatientID");

                    b.HasIndex("PlageHoraireID");

                    b.ToTable("Consultations");

                    b.HasData(
                        new
                        {
                            ConsultationID = 1,
                            PatientID = 1,
                            PlageHoraireID = 1,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 2,
                            PatientID = 2,
                            PlageHoraireID = 1,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 3,
                            PatientID = 3,
                            PlageHoraireID = 2,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 4,
                            PatientID = 4,
                            PlageHoraireID = 2,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 5,
                            PatientID = 5,
                            PlageHoraireID = 3,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 6,
                            PatientID = 6,
                            PlageHoraireID = 3,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 7,
                            PatientID = 7,
                            PlageHoraireID = 4,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 8,
                            PatientID = 8,
                            PlageHoraireID = 4,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 9,
                            PatientID = 9,
                            PlageHoraireID = 5,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 10,
                            PatientID = 10,
                            PlageHoraireID = 5,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 11,
                            PatientID = 11,
                            PlageHoraireID = 6,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 12,
                            PatientID = 12,
                            PlageHoraireID = 6,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 13,
                            PatientID = 13,
                            PlageHoraireID = 7,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 14,
                            PatientID = 14,
                            PlageHoraireID = 7,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 15,
                            PatientID = 15,
                            PlageHoraireID = 8,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 16,
                            PatientID = 16,
                            PlageHoraireID = 8,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 17,
                            PatientID = 17,
                            PlageHoraireID = 9,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 18,
                            PatientID = 18,
                            PlageHoraireID = 9,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 19,
                            PatientID = 19,
                            PlageHoraireID = 10,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 20,
                            PatientID = 20,
                            PlageHoraireID = 10,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 21,
                            PatientID = 21,
                            PlageHoraireID = 11,
                            StatutConsultation = 2
                        },
                        new
                        {
                            ConsultationID = 22,
                            PlageHoraireID = 11,
                            StatutConsultation = 6
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ListeAttente", b =>
                {
                    b.Property<int>("ListeAttenteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListeAttenteID"), 1L, 1);

                    b.Property<int>("CliniqueID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEffectivite")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HeureFermeture")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureOuverture")
                        .HasColumnType("time");

                    b.Property<bool>("IsOuverte")
                        .HasColumnType("bit");

                    b.Property<int>("NbMedecinsDispo")
                        .HasColumnType("int");

                    b.HasKey("ListeAttenteID");

                    b.HasIndex("CliniqueID");

                    b.ToTable("ListeAttentes");

                    b.HasData(
                        new
                        {
                            ListeAttenteID = 1,
                            CliniqueID = 1,
                            DateEffectivite = new DateTime(2024, 1, 31, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9648),
                            HeureFermeture = new TimeSpan(0, 14, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 2,
                            CliniqueID = 2,
                            DateEffectivite = new DateTime(2024, 1, 31, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9661),
                            HeureFermeture = new TimeSpan(0, 8, 30, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 1
                        },
                        new
                        {
                            ListeAttenteID = 3,
                            CliniqueID = 3,
                            DateEffectivite = new DateTime(2024, 1, 31, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9672),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 4,
                            CliniqueID = 4,
                            DateEffectivite = new DateTime(2024, 1, 31, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9681),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 5,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 1, 31, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9690),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 6,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 1, 31, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9700),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 7,
                            CliniqueID = 2,
                            DateEffectivite = new DateTime(2024, 2, 1, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9709),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 8,
                            CliniqueID = 2,
                            DateEffectivite = new DateTime(2024, 2, 1, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9718),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 9,
                            CliniqueID = 3,
                            DateEffectivite = new DateTime(2024, 2, 1, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9727),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 10,
                            CliniqueID = 4,
                            DateEffectivite = new DateTime(2024, 2, 3, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9739),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 11,
                            CliniqueID = 4,
                            DateEffectivite = new DateTime(2024, 2, 4, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9748),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 12,
                            CliniqueID = 4,
                            DateEffectivite = new DateTime(2024, 2, 5, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9757),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 13,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 2, 2, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9766),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 14,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 2, 3, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9775),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 15,
                            CliniqueID = 1,
                            DateEffectivite = new DateTime(2024, 2, 2, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9784),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 16,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 2, 3, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9793),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 17,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 2, 4, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9803),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 18,
                            CliniqueID = 5,
                            DateEffectivite = new DateTime(2024, 2, 5, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9814),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 19,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 1, 31, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9824),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 20,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 2, 1, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9834),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 21,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 2, 2, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9844),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 22,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 2, 3, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9852),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = true,
                            NbMedecinsDispo = 3
                        },
                        new
                        {
                            ListeAttenteID = 23,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 2, 4, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9922),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 2
                        },
                        new
                        {
                            ListeAttenteID = 24,
                            CliniqueID = 6,
                            DateEffectivite = new DateTime(2024, 2, 5, 19, 11, 34, 353, DateTimeKind.Local).AddTicks(9932),
                            HeureFermeture = new TimeSpan(0, 17, 0, 0, 0),
                            HeureOuverture = new TimeSpan(0, 8, 0, 0, 0),
                            IsOuverte = false,
                            NbMedecinsDispo = 3
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("DateDeNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAM")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Age = 32,
                            CodePostal = "J4J 1Z4",
                            DateDeNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Masculin",
                            NAM = "EASC 2342 4332",
                            Nom = "Eastwood",
                            Prenom = "Clint",
                            UserId = "7cc96785-8933-4eac-8d7f-a289b28df223"
                        },
                        new
                        {
                            PatientId = 2,
                            Age = 27,
                            CodePostal = "J4J 1V2",
                            DateDeNaissance = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Féminin",
                            NAM = "BLUE 4232 4332",
                            Nom = "Blunt",
                            Prenom = "Emily",
                            UserId = "e2b8f367-6c94-4a3e-b5a6-45dabec4d2e2"
                        },
                        new
                        {
                            PatientId = 3,
                            Age = 36,
                            CodePostal = "J4J 1G4",
                            DateDeNaissance = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Masculin",
                            NAM = "MARB 3244 2233",
                            Nom = "Brando",
                            Prenom = "Marlon",
                            UserId = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f3f3"
                        },
                        new
                        {
                            PatientId = 4,
                            Age = 44,
                            CodePostal = "J4J 1H6",
                            DateDeNaissance = new DateTime(1980, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Féminin",
                            NAM = "PORT 3443 3433",
                            Nom = "Portman",
                            Prenom = "Natalie",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g4g4"
                        },
                        new
                        {
                            PatientId = 5,
                            Age = 53,
                            CodePostal = "V9S 1N2",
                            DateDeNaissance = new DateTime(1971, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "TREA 1234 4569",
                            Nom = "Tremblay",
                            Prenom = "Anne",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g4g5"
                        },
                        new
                        {
                            PatientId = 6,
                            Age = 28,
                            CodePostal = "C1U 7Y0",
                            DateDeNaissance = new DateTime(1996, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "LAVJ 1234 4570",
                            Nom = "Lavoie",
                            Prenom = "Jean",
                            UserId = "7cc96785-8933-4eac-8d7f-a289b28df226"
                        },
                        new
                        {
                            PatientId = 7,
                            Age = 33,
                            CodePostal = "T5E 4Z2",
                            DateDeNaissance = new DateTime(1991, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "GAGA 1234 4571",
                            Nom = "Gagnon",
                            Prenom = "Andrew",
                            UserId = "e2b8f367-6c94-4a3e-b5a6-45dabec4d2e7"
                        },
                        new
                        {
                            PatientId = 8,
                            Age = 42,
                            CodePostal = "E9C 8W3",
                            DateDeNaissance = new DateTime(1982, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Female",
                            NAM = "GAUJ 1234 4572",
                            Nom = "Gauthier",
                            Prenom = "Jean",
                            UserId = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f3f38"
                        },
                        new
                        {
                            PatientId = 9,
                            Age = 29,
                            CodePostal = "H4Z 0C5",
                            DateDeNaissance = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "ROYS 1234 4573",
                            Nom = "Roy",
                            Prenom = "Sophie",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g4g9"
                        },
                        new
                        {
                            PatientId = 10,
                            Age = 74,
                            CodePostal = "D2R 4Q3",
                            DateDeNaissance = new DateTime(1950, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Female",
                            NAM = "GAGJ 1234 4574",
                            Nom = "Gagnon",
                            Prenom = "Julie",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g410"
                        },
                        new
                        {
                            PatientId = 11,
                            Age = 46,
                            CodePostal = "F1G 2H4",
                            DateDeNaissance = new DateTime(1978, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "BOUM 1234 4575",
                            Nom = "Bouchard",
                            Prenom = "Martin",
                            UserId = "7cc96785-8933-4eac-8d7f-a289b28df211"
                        },
                        new
                        {
                            PatientId = 12,
                            Age = 36,
                            CodePostal = "J3K 5L8",
                            DateDeNaissance = new DateTime(1988, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Female",
                            NAM = "COUA 1234 4576",
                            Nom = "Couto",
                            Prenom = "Anne",
                            UserId = "e2b8f367-6c94-4a3e-b5a6-45dabec4d212"
                        },
                        new
                        {
                            PatientId = 13,
                            Age = 32,
                            CodePostal = "K2L 6M8",
                            DateDeNaissance = new DateTime(1992, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Female",
                            NAM = "FORJ 1234 4577",
                            Nom = "Fortin",
                            Prenom = "Julie",
                            UserId = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f313"
                        },
                        new
                        {
                            PatientId = 14,
                            Age = 30,
                            CodePostal = "X8F 4I7",
                            DateDeNaissance = new DateTime(1994, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Female",
                            NAM = "FORM 1234 4578",
                            Nom = "Fortin",
                            Prenom = "Martin",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g414"
                        },
                        new
                        {
                            PatientId = 15,
                            Age = 39,
                            CodePostal = "S9K 3Z3",
                            DateDeNaissance = new DateTime(1985, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "MORC 1234 4579",
                            Nom = "Morin",
                            Prenom = "Claire",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g415"
                        },
                        new
                        {
                            PatientId = 16,
                            Age = 39,
                            CodePostal = "H3N 3Z8",
                            DateDeNaissance = new DateTime(1985, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "ROYC 1234 4580",
                            Nom = "Roy",
                            Prenom = "Claire",
                            UserId = "7cc96785-8933-4eac-8d7f-a289b28df216"
                        },
                        new
                        {
                            PatientId = 17,
                            Age = 66,
                            CodePostal = "M1F 6Z2",
                            DateDeNaissance = new DateTime(1958, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Female",
                            NAM = "GAUL 1234 4581",
                            Nom = "Gauthier",
                            Prenom = "Louis",
                            UserId = "e2b8f367-6c94-4a3e-b5a6-45dabec4d217"
                        },
                        new
                        {
                            PatientId = 18,
                            Age = 74,
                            CodePostal = "G3W 7Q1",
                            DateDeNaissance = new DateTime(1950, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "COUM 1234 4582",
                            Nom = "Couto",
                            Prenom = "Marie",
                            UserId = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f318"
                        },
                        new
                        {
                            PatientId = 19,
                            Age = 49,
                            CodePostal = "D1D 3D9",
                            DateDeNaissance = new DateTime(1975, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "MORM 1234 4583",
                            Nom = "Morin",
                            Prenom = "Michel",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g419"
                        },
                        new
                        {
                            PatientId = 20,
                            Age = 69,
                            CodePostal = "M4F 2S8",
                            DateDeNaissance = new DateTime(1955, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "ROYM 1234 4584",
                            Nom = "Roy",
                            Prenom = "Martin",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g420"
                        },
                        new
                        {
                            PatientId = 21,
                            Age = 70,
                            CodePostal = "M4F 2S8",
                            DateDeNaissance = new DateTime(1954, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Male",
                            NAM = "ROYM 1234 4585",
                            Nom = "Roy",
                            Prenom = "Matheo",
                            UserId = "g4d0a589-2b02-4d36-9a85-39c028a4g421"
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PatientACharge", b =>
                {
                    b.Property<int>("PatientAChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientAChargeId"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDeNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("NAM")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("PatientAChargeId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientACharges");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PlageHoraire", b =>
                {
                    b.Property<int>("PlageHoraireID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlageHoraireID"), 1L, 1);

                    b.Property<DateTime>("HeureDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HeureFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListeAttenteID")
                        .HasColumnType("int");

                    b.HasKey("PlageHoraireID");

                    b.HasIndex("ListeAttenteID");

                    b.ToTable("PlagesHoraires");

                    b.HasData(
                        new
                        {
                            PlageHoraireID = 1,
                            HeureDebut = new DateTime(2024, 1, 31, 8, 0, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 1, 31, 8, 30, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 2,
                            HeureDebut = new DateTime(2024, 1, 31, 8, 30, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 1, 31, 9, 0, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 3,
                            HeureDebut = new DateTime(2024, 1, 31, 9, 0, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 1, 31, 9, 30, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 4,
                            HeureDebut = new DateTime(2024, 1, 31, 9, 30, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 1, 31, 10, 0, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 5,
                            HeureDebut = new DateTime(2024, 1, 31, 10, 0, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 1, 31, 10, 30, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 6,
                            HeureDebut = new DateTime(2024, 1, 31, 10, 30, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 1, 31, 11, 0, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 7,
                            HeureDebut = new DateTime(2024, 1, 31, 11, 0, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 1, 31, 11, 30, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 8,
                            HeureDebut = new DateTime(2024, 1, 31, 11, 30, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 1, 31, 12, 0, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 9,
                            HeureDebut = new DateTime(2024, 1, 31, 12, 0, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 1, 31, 12, 30, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 10,
                            HeureDebut = new DateTime(2024, 1, 31, 12, 30, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 1, 31, 13, 0, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        },
                        new
                        {
                            PlageHoraireID = 11,
                            HeureDebut = new DateTime(2024, 1, 31, 13, 0, 0, 0, DateTimeKind.Local),
                            HeureFin = new DateTime(2024, 1, 31, 13, 30, 0, 0, DateTimeKind.Local),
                            ListeAttenteID = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "7cc96785-8933-4eac-8d7f-a289b28df223",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e4d68874-8da3-479d-91ff-03adf0f55198",
                            Email = "patient1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT1@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT1@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e2219e7f-cb23-4e1e-a53b-ccf996257a22",
                            TwoFactorEnabled = false,
                            UserName = "patient1@example.com"
                        },
                        new
                        {
                            Id = "e2b8f367-6c94-4a3e-b5a6-45dabec4d2e2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3b3a1e29-79c7-4bc2-97b8-98cb897235b6",
                            Email = "patient2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT2@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT2@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "496d09b2-61e5-457a-a432-36b4cd1a9d21",
                            TwoFactorEnabled = false,
                            UserName = "patient2@example.com"
                        },
                        new
                        {
                            Id = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f3f3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e957cb6a-39df-4c94-9310-830d06f8a8b1",
                            Email = "patient3@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT3@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT3@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4635ef31-03e3-4b36-8f30-a13cd877154b",
                            TwoFactorEnabled = false,
                            UserName = "patient3@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g4g4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7b7bdaf7-78a5-4893-8c6a-1b51452f5758",
                            Email = "patient4@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT4@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT4@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d0995869-e0e9-4c80-bf45-3c3473817244",
                            TwoFactorEnabled = false,
                            UserName = "patient4@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g4g5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7a624313-54aa-4c29-a550-752aab5c0d8a",
                            Email = "patient5@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT5@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT5@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "edd1ee67-e03c-43b4-9ede-6d20b330729e",
                            TwoFactorEnabled = false,
                            UserName = "patient5@example.com"
                        },
                        new
                        {
                            Id = "7cc96785-8933-4eac-8d7f-a289b28df226",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b04aa1a2-1c56-472f-9e59-6fab24997ad8",
                            Email = "patient6@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT6@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT6@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "80edddef-e93d-4efc-9808-29ebb449ff4f",
                            TwoFactorEnabled = false,
                            UserName = "patient6@example.com"
                        },
                        new
                        {
                            Id = "e2b8f367-6c94-4a3e-b5a6-45dabec4d2e7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb517153-0ff6-4ae3-8ec1-80fce888e25f",
                            Email = "patient7@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT7@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT7@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c4466bd8-adba-4fb7-ba19-b064dad63013",
                            TwoFactorEnabled = false,
                            UserName = "patient7@example.com"
                        },
                        new
                        {
                            Id = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f3f38",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "485c9d7c-ad04-401a-b185-84a97b1f53a4",
                            Email = "patient8@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT8@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT8@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "85ded5a1-fc51-4e44-a403-3e72cdf21058",
                            TwoFactorEnabled = false,
                            UserName = "patient8@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g4g9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2f50d3b9-c93a-451a-8fb3-dd9124b5a4ea",
                            Email = "patient9@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT9@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT9@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b6e5150a-4508-4c45-96e4-b3757bec7178",
                            TwoFactorEnabled = false,
                            UserName = "patient9@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g410",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "05e242d0-e011-4e4a-b4fe-f1945421e45a",
                            Email = "patient10@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT10@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT10@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "58026662-43f0-4ed0-a655-46d8838de8cf",
                            TwoFactorEnabled = false,
                            UserName = "patient10@example.com"
                        },
                        new
                        {
                            Id = "7cc96785-8933-4eac-8d7f-a289b28df211",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a09162f8-d341-4b6b-94bc-2e23adacf76b",
                            Email = "patient11@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT11@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT11@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8b2ab376-e04b-4de3-984e-f8ef77fef855",
                            TwoFactorEnabled = false,
                            UserName = "patient11@example.com"
                        },
                        new
                        {
                            Id = "e2b8f367-6c94-4a3e-b5a6-45dabec4d212",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "83f7f026-d7d3-4d13-91ee-1b7706927bc9",
                            Email = "patient12@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT12@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT12@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96306985-6dbe-4f7d-991b-4672f6209eab",
                            TwoFactorEnabled = false,
                            UserName = "patient12@example.com"
                        },
                        new
                        {
                            Id = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f313",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "425a95cf-bf13-4d46-ab1d-29b4d4971ee5",
                            Email = "patient13@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT13@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT13@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d6b99993-d06a-4f8f-9946-4d33463e7ab6",
                            TwoFactorEnabled = false,
                            UserName = "patient13@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g414",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "adc448e8-6ae6-4634-9ead-af08ee17b427",
                            Email = "patient14@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT14@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT14@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b9d836b1-5b56-4b1d-9f85-1f872977eba6",
                            TwoFactorEnabled = false,
                            UserName = "patient14@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g415",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "66d645b3-a6c8-4688-a7ef-9c5b862709b4",
                            Email = "patient15@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT15@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT15@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a8eaca79-09d3-41a2-989d-2759a0e63b8c",
                            TwoFactorEnabled = false,
                            UserName = "patient15@example.com"
                        },
                        new
                        {
                            Id = "7cc96785-8933-4eac-8d7f-a289b28df216",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "600b7f23-c9ed-41c3-b1f7-310387ffd540",
                            Email = "patient16@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT16@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT16@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "97f09654-1828-4559-b844-0f39195bbbd4",
                            TwoFactorEnabled = false,
                            UserName = "patient16@example.com"
                        },
                        new
                        {
                            Id = "e2b8f367-6c94-4a3e-b5a6-45dabec4d217",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "95e6ea02-084d-4095-a0d0-96f821d95275",
                            Email = "patient17@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT17@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT17@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "43383115-d3d7-456f-b5fc-925d07ac7012",
                            TwoFactorEnabled = false,
                            UserName = "patient17@example.com"
                        },
                        new
                        {
                            Id = "f3c9e478-8d81-4aaf-aa77-56e1d3f5f318",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1593ddbb-3a1a-438c-b41c-1b74916f1487",
                            Email = "patient18@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT18@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT18@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f2238dbe-c62e-4cc9-baa9-a109313f0d44",
                            TwoFactorEnabled = false,
                            UserName = "patient18@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g419",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "82a07c7f-0a51-415c-901c-eff38b074709",
                            Email = "patient19@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT19@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT19@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bafa07eb-b0c8-45b5-9441-58e77751436e",
                            TwoFactorEnabled = false,
                            UserName = "patient19@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g420",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d63948b6-408c-41dd-84ff-fd1d8aed54d8",
                            Email = "patient20@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT20@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT20@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb492e30-6e6a-4cc8-b805-353c6d6a19c9",
                            TwoFactorEnabled = false,
                            UserName = "patient20@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g421",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "949777f3-ef7a-4bf4-873d-1f1093515500",
                            Email = "patient21@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT21@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT21@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2e01cc8e-3593-4688-82d6-1e155b8c8190",
                            TwoFactorEnabled = false,
                            UserName = "patient21@example.com"
                        },
                        new
                        {
                            Id = "g4d0a589-2b02-4d36-9a85-39c028a4g22",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4488d9c7-fbae-46a4-be6b-912688a92c91",
                            Email = "patient22@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT22@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT22@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "41d55259-c4ec-42ea-9aaf-c8cac802b37e",
                            TwoFactorEnabled = false,
                            UserName = "patient22@example.com"
                        });
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Clinique", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.Adresse", "Adresse")
                        .WithOne("Clinique")
                        .HasForeignKey("Clinique2000_Core.Models.Clinique", "AdresseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinique2000_Core.Models.ApplicationUser", "Createur")
                        .WithMany("Clinique")
                        .HasForeignKey("CreateurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adresse");

                    b.Navigation("Createur");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Consultation", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.ListeAttente", null)
                        .WithMany("Consultations")
                        .HasForeignKey("ListeAttenteID");

                    b.HasOne("Clinique2000_Core.Models.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientID");

                    b.HasOne("Clinique2000_Core.Models.PlageHoraire", "PlageHorarie")
                        .WithMany("Consultations")
                        .HasForeignKey("PlageHoraireID");

                    b.Navigation("Patient");

                    b.Navigation("PlageHorarie");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ListeAttente", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.Clinique", "Clinique")
                        .WithMany("ListeAttente")
                        .HasForeignKey("CliniqueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinique");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Patient", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.ApplicationUser", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Clinique2000_Core.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PatientACharge", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.Patient", "Patient")
                        .WithMany("PatientsACharge")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PlageHoraire", b =>
                {
                    b.HasOne("Clinique2000_Core.Models.ListeAttente", "ListeAttente")
                        .WithMany("PlagesHoraires")
                        .HasForeignKey("ListeAttenteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListeAttente");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Adresse", b =>
                {
                    b.Navigation("Clinique")
                        .IsRequired();
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Clinique", b =>
                {
                    b.Navigation("ListeAttente");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ListeAttente", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("PlagesHoraires");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.Patient", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("PatientsACharge");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.PlageHoraire", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("Clinique2000_Core.Models.ApplicationUser", b =>
                {
                    b.Navigation("Clinique");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
